### ISSUE TITLE
Tag a release?

### ISSUE THREAD

**Issue by bfontaine** [antirez/redis-tools#9]
Hello,
It would be great to have a tagged release so we could include `redis-tools` in the Homebrew core.
Thanks!

**Comment by antirez** [comment]
Hello @bfontaine! This project is mostly abandonware, and what was worth it was merged into `redis-cli` and `redis-benchmark`, so it's not worth to bother adding it IMHO. Thanks for the interest.

**Comment by antirez** [comment]
p.s. notably `redis-cli --stat`

**Comment by bfontaine** [comment]
Ah, thank you for the notice.
